apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: gcp-infra
  namespace: default
spec:
  components:
    - name: gke-cluster
      type: terraform-gke
      properties:
        name: iac-challenge-gke
        size: small
        project_id: "${GCP_PROJECT_ID}"
        region: "${GCP_REGION}"
      
    - name: postgres-db
      type: terraform-postgresql
      properties:
        name: iac-challenge-postgres
        size: small
        project_id: "${GCP_PROJECT_ID}"
        region: "${GCP_REGION}"
      
  workflow:
    steps:
      - name: deploy-gke
        type: apply-component
        properties:
          component: gke-cluster
      
      - name: deploy-postgres
        type: apply-component
        properties:
          component: postgres-db
        dependsOn:
          - deploy-gke
      
      - name: check-resources
        type: wait
        properties:
          continue: true
          timeout: 600s
        dependsOn:
          - deploy-postgres
