apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: shared-gke-cluster
  namespace: default
spec:
  components:
    - name: gke-cluster
      type: terraform-gke
      properties:
        name: iac-challenge-gke
        size: small
        project_id: "${GCP_PROJECT_ID}"
        region: "${GCP_REGION}"
  
  workflow:
    steps:
      - name: deploy-gke
        type: apply-component
        properties:
          component: gke-cluster
      
      - name: check-gke-ready
        type: wait
        properties:
          continue: true
          timeout: 1200s
          resources:
            - apiVersion: infra.contrib.fluxcd.io/v1alpha2
              kind: Terraform
              name: gke-cluster
          conditions:
            - status: running
              reason: TerraformAppliedCompleted
