apiVersion: terraform.core.oam.dev/v1beta1
kind: Provider
metadata:
  name: gcp-provider
  namespace: vela-system
spec:
  provider: gcp
  credentials:
    source: Secret
    secretRef:
      namespace: flux-system
      name: gcp-credentials
      key: credentials.json
